### PR TITLE
Fix dispatch event to work with contracts

### PR DESCRIPTION
**Pull request by wbloszyk**
## Subject

This PR replace event dispach parameter to work correctly with constracts.

I am targeting this branch, because this change respect BC.

## Changelog

```markdown
### Fixed
- Deprecations for event dispatching
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
You should change: `use Symfony\Component\EventDispatcher\EventDispatcherInterface;` to use the contract.

**Comment by wbloszyk** [comment]
@jordisala1991 
Done. I copy it from AdminBundle. For now version ^2.0 will not be use becouse symfony/event-dispatcher require ^1.1. Anyway support for Symfony5 is close so i keep it here too.

**Comment by wbloszyk** [comment]
@core23 I update test too. Should I do something more?

**Comment by core23** [comment]
Please add a changelog entry, after that it's RTM

**Comment by wbloszyk** [comment]
@core23 Changelog can be like this?

**Comment by core23** [comment]
Thanks @wbloszyk

**Pull request merged**
