### PR TITLE
Fix support for doctrine/doctrine-bundle v2

### PR DESCRIPTION
**Pull request by wbloszyk**
## Subject

I am targeting this branch, because this change respect BC.

## Changelog

```markdown
### Changed
- Change usage of `Symfony\Bridge\Doctrine\RegistryInterface` into `Doctrine\Persistence\ManagerRegistry` (BC)
```

### CODE REVIEW

**Review by dmaicher — APPROVED** [review]

**Review by VincentLanglet — COMMENTED** [review]
Can't we make this work for both ^1 and ^2 ?

**Review by VincentLanglet — APPROVED** [review]

**Comment by wbloszyk** [comment]
@VincentLanglet We can keep ^1 and it will be work for both. Anyway in sandbox (so all ower bundles) we can use ^2. 

We should keep support for 1.x or we can drop support for it becouse we fully support 2.x? WDYT @sonata-project/contributors @greg0ire

**Comment by greg0ire** [comment]
I'm torn: if it means extra work to keep ^1 I wouldn't keep it, but you seem to say it wouldn't. If there are code cleanups we could do by dropping it, then I would drop it.

**Comment by wbloszyk** [comment]
It is RTM.

**Review by VincentLanglet — APPROVED** [review]

**Review by dmaicher — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
Thanks

**Pull request merged**
