### PR TITLE
Fix customer actions PR 2

### PR DESCRIPTION
**Pull request by wbloszyk**
## Subject
Reference to #628 ,but i made mess

I am targeting this branch, because backwards compatible and bug fixes.  [PATCH]
This PR fix bugs after major change (delete method without inject Request).

```php
/**
* NEXT_MAJOR: Remove this method (inject Request $request into actions parameters).
*
* @return Request
*/
private function getCurrentRequest()
{
    return $this->container->get('request_stack')->getCurrentRequest();
}
```

## Changelog

```markdown
### Fixed
- bug with missing CustomerController:getCurrentRequest method
```

### CODE REVIEW

**Comment by wbloszyk** [comment]
@core23 sorry for first PR, now should be BC.

**Comment by greg0ire** [comment]
Can you please check Travis?

**Comment by salamichel** [comment]
@greg0ire it's strange travis failed weir error, could someone check travis configuration?

**Comment by wbloszyk** [comment]
@greg0ire 
This PR also can be merge.

**Comment by greg0ire** [comment]
Thanks @wbloszyk !

**Pull request merged**
