### PR TITLE
Drop SonataCoreBundle

### PR DESCRIPTION
**Pull request by wbloszyk**
## Subject

I am targeting this branch, because it its BC-break.

## Changelog

```markdown
### Removed
- Removed `SonataCoreBundle` 
```

### CODE REVIEW

**Comment by wbloszyk** [comment]
Also I have question about Serializer. Deprecations sugest to using `Sonata\Serializer...` but it is not exist. I Add `Sonata\Component\Serializer\...` insted. It is correct or should we add sonata-project/serializer-extensions?

**Comment by greg0ire** [comment]
>  Deprecations sugest to using Sonata\Serializer...

Where do these deprecations come from?

**Comment by wbloszyk** [comment]
From `Sonata\CoreBundle\Serializer\BaseSerializerHandler`

**Comment by greg0ire** [comment]
I can see a deprecation in here: https://github.com/sonata-project/SonataCoreBundle/blob/3.x/src/Serializer/BaseSerializerHandler.php

but it's not suggesting use `Sonata\Serializer`, is it?

**Comment by wbloszyk** [comment]
I on phone now. I dont remember corebundle version. Anyway shouldnt we move BaseSerializerHandler to form-extensionds? Like `Sonata\Form\Type\BaseDoctrineORMSerializationType` was moved? I will check it monday.

**Comment by greg0ire** [comment]
Not sure what the destination of that type is. @core23 maybe you do?

**Comment by core23** [comment]
AFAIK the serializer is still an open problem. We have to move it to a new repo or find the right place for it.

**Comment by wbloszyk** [comment]
@greg0rite Look at [https://github.com/sonata-project/SonataCoreBundle/blob/3.x/src/CoreBundle/Serializer/BaseSerializerHandler.php](https://github.com/sonata-project/SonataCoreBundle/blob/3.x/src/CoreBundle/Serializer/BaseSerializerHandler.php)

**Comment by greg0ire** [comment]
Let's discuss this at https://github.com/sonata-project/SonataCoreBundle/issues/733 ?

**Comment by wbloszyk** [comment]
Closing this in favor of #672

**Pull request closed without merging**
