### PR TITLE
Increase precision for decimal price fields. Fixes #404

### LINKED ISSUE #404: Default precision in BaseOrder and BaseOrderElement
## Subject

`BaseOrderElement` decimal fields are mapped without specific precision
```xml
<field name="unitPriceExcl" type="decimal" column="unit_price_excl" scale="4"/>
<field name="unitPriceInc" type="decimal" column="unit_price_inc" scale="4"/>
<field name="price" type="decimal" column="price" scale="4"/>
<field name="vatRate" type="decimal" column="vat_rate" scale="4"/>
<field name="designation" type="string" column="designation" length="255"/>
```
Same situation for `BaseOrder`
```xml
<field name="totalInc" nullable="true" type="decimal" column="total_inc" scale="4"/>
<field name="totalExcl" nullable="true" type="decimal" column="total_excl" scale="4"/>
<field name="deliveryCost" nullable="true" type="decimal" column="delivery_cost" scale="4"/>
<field name="deliveryVat" nullable="true" type="decimal" column="delivery_vat" scale="4"/>
```

By default in mysql and postgresql precision for decimal fields is equal to 10. So if we have an order or an order element with totalPrice over than 10^6 it will fail while inserting into the database.

## Steps to reproduce

Create a product with price 500 000
Add it to the basket
Set quantity to 20
Try to make an order

## Expected results
Created order

## Actual results
Database inserting fail

## Current fix
Override attributes in `Application\Sonata\OrderBundle\Entity\Order`
```php
/**
 * Class Order
 * @ORM\Entity()
 * @ORM\Table(name="order__order")
 * @ORM\AttributeOverrides({
 *      @ORM\AttributeOverride(name="totalInc",
 *          column=@ORM\Column(nullable= true, type="decimal", name="total_inc", scale=4, precision=20)
 *      ),
 *     @ORM\AttributeOverride(name="totalExcl",
 *          column=@ORM\Column(nullable= true, type="decimal", name="total_excl", scale=4, precision=20)
 *      ),
 *     @ORM\AttributeOverride(name="deliveryCost",
 *          column=@ORM\Column(nullable= true, type="decimal", name="delivery_cost", scale=4, precision=20)
 *      ),
 *     @ORM\AttributeOverride(name="deliveryVat",
 *          column=@ORM\Column(nullable= true, type="decimal", name="delivery_vat", scale=4, precision=20)
 *      )
 * })
 */
class Order extends BaseOrder
...
```
Override attributes in `Application\Sonata\OrderBundle\Entity\OrderElement`
```php
/**
 * Class OrderElement
 * @ORM\Entity()
 * @ORM\Table(name="order__order_element")
 * @ORM\AttributeOverrides({
 *      @ORM\AttributeOverride(name="unitPriceExcl",
 *          column=@ORM\Column(type="decimal", name="unit_price_excl", scale=4, precision=20)
 *      ),
 *     @ORM\AttributeOverride(name="unitPriceInc",
 *          column=@ORM\Column(type="decimal", name="unit_price_inc", scale=4, precision=20)
 *      ),
 *     @ORM\AttributeOverride(name="price",
 *          column=@ORM\Column(type="decimal", name="price", scale=4, precision=20)
 *      ),
 *     @ORM\AttributeOverride(name="vatRate",
 *          column=@ORM\Column(type="decimal", name="vat_rate", scale=4, precision=20)
 *      )
 * })
 */
class OrderElement extends BaseOrderElement
...
```

### PR DESCRIPTION
**Pull request by ZRazor**
## Changelog

```markdown
### Fixed
- Increase precision for decimal price fields in BaseProduct, BaseOrder, BaseOrderElement
```

Fixes #404

### CODE REVIEW

**Comment by greg0ire** [comment]
Does this imply any schema migration?

**Comment by ZRazor** [comment]
@greg0ire, yes - doctrine migration is required

**Comment by greg0ire** [comment]
Then this is major, and should be done on the master branch I think.

**Comment by greg0ire** [comment]
You can change the base branch of your PR with the Edit button.

**Comment by OskarStark** [comment]
Please add a note to the UPGRADE.md file

**Comment by ZRazor** [comment]
@OskarStark, at the current moment there are `UPGRADE-2.x.md` and `UPGRADE-2.0.md`
Should I create `UPGRADE-3.0.md` or `UPGRADE.md`?

**Comment by ZRazor** [comment]
@OskarStark, no need to answer, I swtiched to master branch - UPGRADE-3.0  is there

**Comment by OskarStark** [comment]
Thank you @ZRazor 👍

**Pull request merged**
