### PR TITLE
change validator context of product entity

### PR DESCRIPTION
**Pull request by bdejacobet**
Fixing issue #293

(fix done by @utilisezlinux but there was a problem with his PR )

### CODE REVIEW

**Comment by rande** [comment]
@bdejacobet not sure it is the correct class: ``https://github.com/symfony/Validator/blob/master/Context/ExecutionContextInterface.php``

**Comment by utilisezlinux** [comment]
According to https://github.com/symfony/Validator/tree/master/Context, LegacyExecutionContext.php and ExecutionContext.php are deprecated and to be suppressed in symfony 3.0.
The advice given by Bernhard Schussek <bschussek@gmail.com> is `not to instantiate or use this class. Code against {@link ExecutionContextInterface} instead.`
The fixing works for me with changes in`https://github.com/sonata-project/ecommerce/blob/master/src/ProductBundle/Entity/BaseProduct.php` and in `https://github.com/sonata-project/ecommerce/blob/master/src/Component/Product/ProductInterface.php`.

Should we use this fix temporarily or modify the call of validateOneMainCategory() to pass ExecutionContext instead of LegacyExecutionContext to it?

**Comment by bdejacobet** [comment]
@rande change to Symfony\Component\Validator\ExecutionContextInterface

**Comment by rande** [comment]
Thanks

**Pull request merged**
