### PR TITLE
add discriminator field name for JMS serializer

### PR DESCRIPTION
**Pull request by Filoz**
I am targeting this branch, because  this is a bug fix.

## Changelog

```markdown
### Added
- Added `discriminator-field-name` to fix JMS Serializer compatibility

```

## Subject

I added the 'discriminator-field-name'  in the product seralizer skelton as specified in [JMS Serializer documentation](http://jmsyst.com/libs/serializer/master/reference/xml_reference)  because without it throwed an exception ["The $fieldName cannot be empty."](https://github.com/schmittjoh/serializer/blob/master/src/Metadata/ClassMetadata.php#L69)

### CODE REVIEW

**Comment by greg0ire** [comment]
Please remove the markdown from your commit message

**Comment by Filoz** [comment]
done :)

**Comment by Filoz** [comment]
According to https://travis-ci.org/sonata-project/ecommerce/jobs/234043283 I have to remove the line break?

**Comment by core23** [comment]
> According to https://travis-ci.org/sonata-project/ecommerce/jobs/234043283 have I to remove the line break?

That's right!

**Comment by Filoz** [comment]
is it ok? :)

**Comment by greg0ire** [comment]
Yes it is, thanks @Filoz !

**Pull request merged**
