### PR TITLE
Fix interface compatibility

### PR DESCRIPTION
**Pull request by MrGreenStuff**

### CODE REVIEW

**Comment by rande** [comment]
@MrGreenStuff is this change compatible with symfony 2.6 ?

**Comment by sergiostrampelli** [comment]
Using Symfony 2.6, I have patched with:

    public function validateOneMainCategory(ExecutionContextInterface $context)

**Comment by MrGreenStuff** [comment]
Ok for 2.6

**Comment by rande** [comment]
Does that work for symfony 2.3 too ? (this is the minimun requirements in the composer.json)

**Pull request closed without merging**
