### PR TITLE
fixed some relations

### PR DESCRIPTION
**Pull request by quisse**
## Subject

I am targeting this branch, because backwards compatible.

## Changelog

```markdown
### Fixed
Missing relations
```

### CODE REVIEW

**Comment by greg0ire** [comment]
What is broken and how was this relationship missing? All relationships need not be bidirectional. In fact, bidirectional relationship are not precisely recommended.

**Comment by quisse** [comment]
@greg0ire based on suggestions from the Symfony profiler... The profiler shows following for example: 
Untitled
So to me it seems like that there's something wrong. Maybe I get this wrong?

**Comment by greg0ire** [comment]
Oh indeed, you can't really have unidirectional 1-to-n relationships: https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-many-unidirectional-with-join-table, I think your fix is easiest way to get us closer to something correct.

**Comment by OskarStark** [comment]
Thank you

**Comment by quisse** [comment]
Great! ☺️

**Pull request merged**
