### PR TITLE
Typo transformer events

### PR DESCRIPTION
**Pull request by stphnpt**
Same as #334

### CODE REVIEW

**Comment by OskarStark** [comment]
Good catch @stphnpt 👍 

LGTM!

**Comment by OskarStark** [comment]
Not sure if `develop` is the correct target branch!

/cc @greg0ire @core23 @Soullivaneuh

**Comment by stphnpt** [comment]
@OskarStark the Events directory in Component (that bundles all events) only exists in develop branch

**Comment by core23** [comment]
This project looks a little strange... We have commits in all branches that only exists once.

bildschirmfoto 2016-06-18 um 15 33 02

**Comment by Soullivaneuh** [comment]
Branches need to be refactored.

Don't know how for the moment.

https://github.com/sonata-project/dev-kit/issues/138

**Pull request closed without merging**
