### PR TITLE
Fix: DOCtor-RST build (nelmio/api-doc-bundle router)

### PR DESCRIPTION
**Pull request by wbloszyk**

### CODE REVIEW

**Comment by OskarStark** [comment]
This needs to be added to dev-kit first

**Comment by wbloszyk** [comment]
> This needs to be added to dev-kit first

Done:
https://github.com/sonata-project/dev-kit/pull/893

**Comment by OskarStark** [comment]
Thank you

**Comment by OskarStark** [comment]
Will be fixed by dev-kit soon.
Closing here.

Thank you

**Pull request closed without merging**
