### PR TITLE
use AbstractAdmin instead of deprecated Admin class

### PR DESCRIPTION
**Pull request by OskarStark**
I am targetting this branch, because this is BC.

## Changelog

```markdown
### Deprecated
- Use `AbstractAdmin` instead of deprecated `AdminClass` and added dependency for `SonataAdminBundle`
```

### CODE REVIEW

**Comment by OskarStark** [comment]
patch or minor?

**Comment by greg0ire** [comment]
Patch, because we should not have any deprecations.

**Comment by OskarStark** [comment]
Rebased

**Comment by greg0ire** [comment]
Thanks @OskarStark !

**Pull request merged**
