### PR TITLE
removed use of deprecated trans function

### PR DESCRIPTION
**Pull request by quisse**
## Subject

I am targeting this branch, because not backwards compatible.

## Changelog

```markdown
### Changed
- removed use of deprecated function
```

### CODE REVIEW

**Comment by core23** [comment]
> I am targeting this branch, because not backwards compatible.

Sure? IFAIK the translator will always be called

**Comment by quisse** [comment]
Could be. Shall i retarget?

**Comment by core23** [comment]
Please test it and pick the right branch afterwards

**Comment by core23** [comment]
Can you please fix the tests @quisse

**Comment by quisse** [comment]
It’s a bit unclear what I can do to fix it. Could anyone point me in the right direction please?

**Comment by core23** [comment]
Have you tried to rebase @quisse ?

**Comment by greg0ire** [comment]
Thanks @quisse !

**Pull request merged**
