### PR TITLE
Fix resetting full basket stored in session

### LINKED ISSUE #450: Basket is  is not emptied when payment process is completed
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.18.2
sonata-project/block-bundle              3.3.2
sonata-project/cache                     1.0.7
sonata-project/classification-bundle     3.3.0
sonata-project/core-bundle               3.4.0
sonata-project/datagrid-bundle           2.2.1
sonata-project/doctrine-extensions       1.0.2
sonata-project/doctrine-orm-admin-bundle 3.1.4
sonata-project/easy-extends-bundle       2.2.0
sonata-project/exporter                  1.7.1
sonata-project/formatter-bundle          3.2.0
sonata-project/intl-bundle               2.x-dev 90e304f
sonata-project/media-bundle              3.5.1
sonata-project/notification-bundle       3.1.0
sonata-project/seo-bundle                2.x-dev 43c4437
sonata-project/user-bundle               dev-master 34a771f

```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v3.2.8  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.1  Symfony SwiftmailerBundle
symfony/symfony            v3.2.8  The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.0.15 (cli) (built: Jan 17 2017 13:58:38) ( ZTS )
```

## Subject
After payment complete, the basket soul be emptied

## Steps to reproduce
Add a product to basket, complete checkout process
Go to basket, the product will be still here 
## Expected results
The basket has no products

### PR DESCRIPTION
**Pull request by ZRazor**
I am targeting this branch, because it's a bug fix.

Closes #450 

## Changelog

```markdown
### Fixed
- Fixed resetting full basket stored in session
- Removed duplicated code from `BasketSessionFactory`
```

## Subject

The reason of this bug is described in my message in #450

### CODE REVIEW

**Comment by greg0ire** [comment]
1. There should be 2 commits
2. "The reason of this bug is described in my message in #450 " the full reason should be explained in one of the commit messages. Please make it so that your change can be fully understood just by having a look at the gitlog. You can add references to Github issues, but as an optional bonus.

**Comment by ZRazor** [comment]
@greg0ire done

**Comment by greg0ire** [comment]
Great job!

**Comment by ZRazor** [comment]
@jordisala1991 @greg0ire testcase added

**Comment by OskarStark** [comment]
Thanks @ZRazor 👍

**Pull request merged**
