### PR TITLE
Fix jQuery add_basket form selector. Resolves #405

### LINKED ISSUE #405: Modal adding products in view.html.twig and view_thumbnail.html.twig
## Subject

`ProductBundle:Product:view.html` uses `SonataBasketBundle:Basket:add_product_form.html.twig`
and
`ProductBundle:Product:view_thumbnail.html` uses `SonataBasketBundle:Basket:add_product_form_button.html.twig`

They both use `bundles/sonatabasket/modal.js`
where form is selected by id `jQuery('form#form_add_basket')`
but the definition of the form in `add_product_form_button` is `form id="form_add_basket_button_{{ product.id }}"`
So modal adding wont work in thumbnail mode.

## Solution
Replace form selector with `jQuery('form[id^="form_add_basket"]')`

### PR DESCRIPTION
**Pull request by ZRazor**
Fix jQuery `add_basket_button` form  selector for `ProductBundle:Product:view.html` and `ProductBundle:Product:view_thumbnail.html`
Resolves #405

### CODE REVIEW

**Comment by ZRazor** [comment]
I tried to figure out, why tests failed on php <= 5.5, and not failed 19 days ago (last build). Thats what I found:
Tests fail here inside DataGridBundle (2.2.1) `Sonata\DatagridBundle\Pager\Doctrine\Pager`
```
    public function computeNbResult()
    {
        ...
        $countQuery->select(sprintf(
            'count(DISTINCT %s.%s) as cnt',
            current($countQuery->getRootAliases()),
            current($this->getCountColumn())
        ));
```
But 2.2.1 version was released only 17 days ago, and before this code looks like:
```
    public function computeNbResult()
    {
        ...
        $countQuery->select(sprintf('count(DISTINCT %s.%s) as cnt', $countQuery->getRootAlias(), current($this->getCountColumn())));
```
The problem is in `getRootAlias()` and `getRootAliases()` functions.

Quick solution:
Fix composer.json at ` "sonata-project/datagrid-bundle": "2.2.0"`

Good solution:
Figure out, what happened

@greg0ire, what do you think?

**Comment by jordisala1991** [comment]
This is what needs to be done to fix those tests: https://github.com/sonata-project/SonataMediaBundle/pull/1194

**Comment by ZRazor** [comment]
@jordisala1991, thanks
I'll make a new PR with tests fix

**Comment by jordisala1991** [comment]
Let's trigger again build? oh, wait, you will have to rebase first 😄  my bad

**Comment by ZRazor** [comment]
@jordisala1991 rebase - done

**Comment by greg0ire** [comment]
Thanks @ZRazor !

**Pull request merged**
